### ISSUE TITLE
Build failed on Linux 64bit Node v6

### ISSUE THREAD

**Issue by junwatu** [mrgodhani/rss-reader#13]
Hello, i have build error message on Ubuntu Trusty 64bit with node 6.2.2
```
$ npm run release

> @ release /home/equan/Downloads/rss-reader-2.0
> npm run build && npm run package

> @ build /home/equan/Downloads/rss-reader-2.0
> rimraf dist && mkdirp dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js

> @ package /home/equan/Downloads/rss-reader-2.0
> node build/package.js

Packaging app for platform linux ia32 using electron v1.1.0
{ Error: Command failed: npm prune --production
npm ERR! Linux 4.2.0-38-generic
npm ERR! argv "/home/equan/.nvm/v6.2.2/bin/node" "/home/equan/Downloads/rss-reader-2.0/node_modules/.bin/npm" "prune" "--production"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! path /tmp/equan/electron-packager/linux-ia32/RSS Reader-linux-ia32/resources/app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/equan/electron-packager/linux-ia32/RSS Reader-linux-ia32/resources/app/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/equan/electron-packager/linux-ia32/RSS Reader-linux-ia32/resources/app/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/equan/electron-packager/linux-ia32/RSS Reader-linux-ia32/resources/app/npm-debug.log

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 254,
  signal: null,
  cmd: 'npm prune --production' }

npm ERR! Linux 4.2.0-38-generic
npm ERR! argv "/home/equan/.nvm/v6.2.2/bin/node" "/home/equan/Downloads/rss-reader-2.0/node_modules/.bin/npm" "run" "package"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! @ package: `node build/package.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ package script 'node build/package.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/package.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/equan/Downloads/rss-reader-2.0/npm-debug.log

npm ERR! Linux 4.2.0-38-generic
npm ERR! argv "/home/equan/.nvm/v6.2.2/bin/node" "/home/equan/.nvm/v6.2.2/bin/npm" "run" "release"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! @ release: `npm run build && npm run package`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ release script 'npm run build && npm run package'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run package
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
```

**Comment by mrgodhani** [comment]
Interesting I ran on my Macbook it packages well . Although in error it mentions to get latest version of node `npm ERR! Make sure you have the latest version of node.js and npm installed.`

Current npm version is 3.10 and node is 6.3. Did you trying deleting node_modules and reinstall it? and then package?

**Comment by mrgodhani** [comment]
Nvm I will fix it.

**Comment by mrgodhani** [comment]
ok that error might be due to node-sass run ` npm rebuild node-sass` and let me know if it works afterwords.

**Comment by junwatu** [comment]
Ah yes, i think that did the trick. It run great with the latest node v.6.3 too. Thanks for the project.
