### ISSUE TITLE
Install on Macbook El Capitan

### ISSUE THREAD

**Issue by chadwtkns** [mrgodhani/rss-reader#15]
Ive been trying to install the reader on my macbook and am getting the following error. I have the electron prebinaries installed as a dev dependency (v1.1.0)

```
npm run release

> @ release /Users/cwatkins/github/rss-reader
> npm run build && npm run package


> @ build /Users/cwatkins/github/rss-reader
> rimraf dist && mkdirp dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js

  0% compile/Users/cwatkins/github/rss-reader/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^

TypeError: Cannot read property 'uid' of undefined
    at /Users/cwatkins/github/rss-reader/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! @ build: `rimraf dist && mkdirp dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'rimraf dist && mkdirp dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && mkdirp dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cwatkins/github/rss-reader/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "release"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! @ release: `npm run build && npm run package`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ release script 'npm run build && npm run package'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run package
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cwatkins/github/rss-reader/npm-debug.log

```

**Comment by mrgodhani** [comment]
@chadwtkns  Try updating your node version to latest and let me know if it works or not

**Comment by chadwtkns** [comment]
Ive upgraded to v4.5.0 LTS and it didn't work, or do you mean to upgrade to the 6.0 line?

**Comment by mrgodhani** [comment]
@chadwtkns yes try that

**Comment by chadwtkns** [comment]
@mrgodhani I just updated 6.6.0 and that didn't work, is there a specific version of electron that I need?

**Comment by mrgodhani** [comment]
Very strange works fine on mine on new macOs too. What's your npm version ?

**Comment by chadwtkns** [comment]
Ive tried it with both 2.14.12 and with 3.10.3 with node versions mentioned above respectively

**Comment by mrgodhani** [comment]
My npm version is 3.10.7

**Comment by chadwtkns** [comment]
ok, what version of electron are you using?

**Comment by chadwtkns** [comment]
have i missed a step you think? Here is all the commands that I have run to get this project

git clone <repo>
cd rss-reader
npm install electron --save-dev
npm install
npm run release

**Comment by mrgodhani** [comment]
@chadwtkns it is strange I have latest electron installed globally and still working for me. On your end main cause of error is following : 

```
TypeError: Cannot read property 'uid' of undefined
    at /Users/cwatkins/github/rss-reader/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```
Which I am not sure why would happen. I reinstalled my node_modules and it is working perfect.
